from setuptools import setup, find_packages

setup(
    name='ELOISA',
    version='0.1.0',
    author='Juan Esteban Lamilla',
    author_email='juan.e.lamilla@gmail.com',
    description='Unsupervised Temporal Analysis of Satellite Imagery through CNN and Clustering',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/JuanesLamilla/ELOISA',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    include_package_data=True,
    install_requires=[
        'earthengine-api==0.1.393',
        'earthpy==0.9.4',
        'folium==0.14.0',
        'geemap==0.32.0',
        'geopandas==0.14.2',
        'matplotlib==3.8.0',
        'numpy==1.26.4',
        'pandas==2.2.1',
        'rasterio==1.3.9',
        'seaborn==0.12.2',
        'scikit-learn==1.3.0',
        'shapely==2.0.3',
        'pysal==2.1.0',
        'splot==1.1.6',
        'netgraph',
        'progressbar2==4.4.2',
        'spams-bin==2.6.10',
        'networkx==3.1',
        'scikit-optimize==0.10.2',
        'tensorflow==2.16.1',
        'pysan==0.22.1',
        'xgboost==2.1.1'
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.12.2',
)